### ISSUE TITLE
无法发现设备

### ISSUE THREAD

**Issue by wwj718** [marklogg/mini_demo#1]
alphamini依赖于 zeroconf ，zeroconf 在 windows设备下，似乎很容易出问题，诸如切换一下网络，就无法发现设备。

在3台windows 10 设备上稳定复现。

同样的设备上 ucodelink（好像是基于js构建） 工作正常， 是否考虑修复zeroconf相关bug？

**Comment by llllhd** [comment]
> alphamini依赖于 zeroconf ，zeroconf 在 windows设备下，似乎很容易出问题，诸如切换一下网络，就无法发现设备。
> 
> 在3台windows 10 设备上稳定复现。
> 
> 同样的设备上 ucodelink（好像是基于js构建） 工作正常， 是否考虑修复zeroconf相关bug？

你好，请问你在Windows上成功连接了机器人吗？

**Comment by lexcorp** [comment]
@wwj718 Were you able to solve this problem?

**Comment by lexcorp** [comment]
Hello @wwj718, I solved this in two ways, the first time I restarted my computer, in my case I use Windows 10, after restarting I managed to connect to the robot.

The second time it was necessary to restart the robot, after restarting it I was able to connect to it.

It's probably related to zeroconf as you mention.

**Comment by wwj718** [comment]
Thank you for sharing your solution. Zeroconf seems to stop working after running for a while.
